services:
  postgres:
    image: "postgres:13-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
